name: Deploy CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configura chave SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy no servidor
        run: |
          ssh -o StrictHostKeyChecking=no elders787@systemdev.com.br "
            cd /var/www/app-teste-ci &&
            git pull origin main &&
            composer install --no-dev --optimize-autoloader &&
            php spark migrate --all
          "
